apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  namespace: poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      automountServiceAccountToken: false
      containers:
        - name: httpd-container
          image: httpd:2.4
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: livenessProbe
                  value: OK
  strategy:
    type: Recreate
