apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: httpd-app
  template:
    metadata:
      labels:
        app: httpd-app
    spec:
      securityContext:
        runAsUser: 1001
      containers:
      - name: httpd-container
        image: httpd
        resources:
          limits:
            memory: 256Mi
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
  strategy:
    type: Recreate
