# Variable 'aws_access_key_id' was defined in the Variables tab
# Variable 'aws_secret_access_key' was defined in the Variables tab
# Variable 'backend_config_bucket' was defined in the Variables tab
# Variable 'backend_config_key' was defined in the Variables tab
# Variable 'backend_config_region' was defined in the Variables tab
resources:
  repositories:
  - repository: self
    type: git
    ref: main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: TerraformInstaller@0
    displayName: Install Terraform 0.15.3
    inputs:
      terraformVersion: 0.15.3
  - task: TerraformTaskV1@0
    displayName: 'Terraform : init'
    inputs:
      provider: aws
      workingDirectory: $(System.DefaultWorkingDirectory)\terraform\deployments\prod
      backendServiceAWS: bd92def8-a23a-4f6e-956a-b48571b2fbab
      backendAWSBucketName: $(backend_config_bucket)
      backendAWSKey: $(backend_config_key)
  - task: TerraformTaskV1@0
    displayName: 'Terraform : plan'
    inputs:
      provider: aws
      command: plan
      workingDirectory: $(System.DefaultWorkingDirectory)\terraform\deployments\prod
      commandOptions: -var "access_key=$(aws_access_key_id)" -var "secret_key=$(aws_secret_access_key)" -out terraform_plan.tfplan
      environmentServiceNameAWS: bd92def8-a23a-4f6e-956a-b48571b2fbab
  - task: TerraformTaskV1@0
    displayName: 'Terraform : validate and apply'
    enabled: False
    inputs:
      provider: aws
      command: apply
      workingDirectory: $(System.DefaultWorkingDirectory)\terraform\deployments\prod
      commandOptions: '"terraform_plan.tfplan"'
      environmentServiceNameAWS: bd92def8-a23a-4f6e-956a-b48571b2fbab
  - task: TerraformTaskV1@0
    displayName: 'Terraform : destroy'
    enabled: False
    inputs:
      provider: aws
      command: destroy
      workingDirectory: $(System.DefaultWorkingDirectory)\terraform\deployments\prod
      commandOptions: -var "access_key=$(aws_access_key_id)" -var "secret_key=$(aws_secret_access_key)"
      environmentServiceNameAWS: bd92def8-a23a-4f6e-956a-b48571b2fbab
...
