name: AWS Terraform

on: [push, pull_request, workflow_dispatch]

jobs:
  terraform:
    name: AWS Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/aws/deployments/dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Verify Terraform version
        id: version
        run: terraform --version

      - name: Terraform Format
        id: format
        run: terraform fmt -check

      - name: Terraform init
        id: init
        run: terraform init -input=false

      - name: Terraform validation
        id: validation
        run: terraform validate

      - name: Terraform plan
        id: plan
        run: terraform plan
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Run Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/aws/

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve
